### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jorgeal94** [X-Stuff/CudaKeeloq#2]
It´s possible to mod the code to calculate seed from one remote if we know the manufacturer code? Talking about FAAC,BFT,ERREKA....
I think it´s a better application, because seed has only 32 bits, so 4.294.967.295 possible seeds to check, if you archieve to check at same speed than manufacturer codes you could take a seed in 19 secs...  
Thanks in advance!

**Comment by X-Stuff** [comment]
Yeah. it's possible to do, although it wasn't designed.
Also, this kind of brute could be made on CPU...

I'll look into this issue, but can't promise any date.

You may look into `src\host\host_utils.cpp`:`line 22`
``` 
    // TODO: Support as <key>:<seed>
    constexpr uint32_t SEED_UNSUPPORTED = 0;
```
It's code for reading dictionary in text mode.

So if you need it quick - you can just code it by yourself and prepare dictionary file by yourself:
```
<man>:0
<man>:1
<man>:2
...
```
Yeah, the dict file will be pretty huge in that case, but it would be better option if you need it *right now*.

Full support for seeds and bruteforce was in my plans, but it may take month(s) before I'll **start** to do it

**Comment by jorgeal94** [comment]
I know that it can be done in CPU, I have a program that makes it, but it´s slow, maybe 1-2 days to take the key...
With your implementation it will be so much faster! If you want I could send you mine if it helps you to make it easier
I never went into kernel programming so IDK where to start, but I can try it with your advises... Thanks so much!

**Comment by X-Stuff** [comment]
Hi, it was a free weekend so, I did (I hope) what you asked for.
use release-v0.1.1
You should use `--mode=5 --start=<key>`. More details see in updated readme.

**Comment by roberodin** [comment]
> It´s possible to mod the code to calculate seed from one remote if we know the manufacturer code? Talking about FAAC,BFT,ERREKA.... I think it´s a better application, because seed has only 32 bits, so 4.294.967.295 possible seeds to check, if you archieve to check at same speed than manufacturer codes you could take a seed in 19 secs... Thanks in advance!

Hi Jorge, do you have the manufacturer codes? Especially Erreka? Could you share them? Thanks!
